{"name": "Open page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'ВТ-1003 \"Черника\" - чм')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given website '/'", "status": "passed", "start": 1518619166708, "stop": 1518619168125}, {"name": "Then clear by id 'search_input'", "status": "passed", "start": 1518619168125, "stop": 1518619169155}, {"name": "Then insert by id 'search_input' 'вт-1003'", "status": "passed", "start": 1518619169155, "stop": 1518619169265}, {"name": "Then page wait '5'", "status": "passed", "start": 1518619169265, "stop": 1518619174270}, {"name": "Then find element 'a' with text 'ВТ-1003 \"Черника\" - чм'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'ВТ-1003 \"Черника\" - чм')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1518619174270, "stop": 1518619174810}], "attachments": [{"name": "screenshot", "source": "43b8988a-3c91-4fd3-99ee-a58ff3a7c39e-attachment.png", "type": "image/png"}], "parameters": [{"name": "text", "value": "вт-1003"}, {"name": "result", "value": "ВТ-1003 \"Черника\" - чм"}], "start": 1518619166708, "stop": 1518619175131, "uuid": "66356bca-6020-4cf0-97b9-0fb877730161", "historyId": "08522aa31353c05f5e4ddc0fb1153e55", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Checking qsearch"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}