{"name": "Try to search", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given website 'https://www.mirkrestikom.ru/'", "status": "passed", "start": 1518615584700, "stop": 1518615585866}, {"name": "Then clear by id 'search_input'", "status": "passed", "start": 1518615585866, "stop": 1518615586214}, {"name": "Then insert by id 'search_input' '-000575'", "status": "passed", "start": 1518615586214, "stop": 1518615586315}, {"name": "Then push on button by id 'search_submit'", "status": "passed", "start": 1518615586315, "stop": 1518615587552}, {"name": "Then page wait '3'", "status": "passed", "start": 1518615587553, "stop": 1518615590553}, {"name": "Then find element 'a' with text 'MI-000575 Карнавальная ночь'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'MI-000575 Карнавальная ночь')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1518615590553, "stop": 1518615590568}], "attachments": [{"name": "screenshot", "source": "9dd5af2f-6a76-4146-b424-5e0483e6ef91-attachment.png", "type": "image/png"}], "parameters": [{"name": "text", "value": "-000575"}, {"name": "result", "value": "MI-000575 Карнавальная ночь"}], "start": 1518615584699, "stop": 1518615590636, "uuid": "3226579c-f7d6-48b5-8d63-adde36987e44", "historyId": "7e1555743fbbc80d0ce8c073e1d4b61b", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Checking search (step)"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}