{"name": "Open page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'CU029 - Сердцеед')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given website '/'", "status": "passed", "start": 1518619159531, "stop": 1518619161275}, {"name": "Then clear by id 'search_input'", "status": "passed", "start": 1518619161275, "stop": 1518619161359}, {"name": "Then insert by id 'search_input' 'CU029'", "status": "passed", "start": 1518619161359, "stop": 1518619161387}, {"name": "Then page wait '5'", "status": "passed", "start": 1518619161387, "stop": 1518619166388}, {"name": "Then find element 'a' with text 'CU029 - Сердцеед'", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //a[contains(text(), 'CU029 - Сердцеед')]\n\n", "trace": "  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\behave\\model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"step_test.py\", line 68, in step\n    \"//%s[contains(text(), '%s')]\" % (tag, text))\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 855, in find_element\n    'value': value})['value']\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\user\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 194, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1518619166388, "stop": 1518619166388}], "attachments": [{"name": "screenshot", "source": "4564aa73-b8c5-432e-8d1c-be06f18192e1-attachment.png", "type": "image/png"}], "parameters": [{"name": "text", "value": "CU029"}, {"name": "result", "value": "CU029 - Сердцеед"}], "start": 1518619159530, "stop": 1518619166708, "uuid": "3f1f96cc-859f-401f-bde9-837741a42080", "historyId": "5f543a979dd3abf0e68bad3cce600bb8", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Checking qsearch"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}